### ISSUE TITLE
Experimental details on CarRacing

### ISSUE THREAD

**Issue by kimhc6028** [Anjum48/rl-examples#4]
Hi, thank you for your great works. This is the best repo that beats CarRacing.
I thought CarRacing results best performance with ppo_lstm_joined.py, but how long did it take to train? Is number of episode of 10000 enough? I just want to make sure before training it myself....

**Comment by Anjum48** [comment]
Hi, thank you very much! I usually trained to about 4000 episodes, but I found that performance would ramp up to about 500 episodes before becoming unstable (you might get a handful of episodes > 900). I'm not entirely sure why (maybe due to https://github.com/Anjum48/rl-examples/issues/3) but if you have any ideas, let me know and I'll test/update

![screenshot from 2018-09-27 16-34-29](https://user-images.githubusercontent.com/13783303/46149626-69642b00-c273-11e8-9872-ce37c74f56e1.png)

**Comment by kimhc6028** [comment]
Thank you!! If I can find any improvements luckily, I will report it!
